#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

blockMesh

surfaceFeatureExtract

snappyHexMesh -overwrite

#------------------------------------------------------------------------------
